### ISSUE TITLE
exceptions being thrown on call to `element.matches()` when element == null

### ISSUE THREAD

**Issue by boxxxie** [unpoly/unpoly#198] opened 2021-06-26 18:39 UTC
### Bug description

getting null errors, looks like they are from `selector.closest` trying to get the parent of `<html>`
if it's not from `selector.closest` then at least the logic is similar from my printouts (recursive parent, even if parent is null, and exec some function `.matches()` in this case.

this is happening when i'm swapping out a `up-main` fragment.

unpoly `2.0.1`, upgraded from `0.62` where this error wasn't being thrown.

```
unpoly.js:2440 Uncaught (in promise) TypeError: Cannot read property 'matches' of null
    at Object.matches (unpoly.js:2440)
    at Object.isRoot (unpoly.js:16086)
    at RevealMotion.up.RevealMotion.RevealMotion.getViewportRect (unpoly.js:10739)
    at RevealMotion.up.RevealMotion.RevealMotion.start (unpoly.js:10700)
    at start (unpoly.js:8220)
    at mutedAnimator (unpoly.js:8179)
    at MotionController.up.MotionController.MotionController.whileForwardingFinishEvent (unpoly.js:8314)
    at MotionController.whileForwardingFinishEvent (unpoly.js:8124)
    at unpoly.js:8189
```

**Comment by adam12** [comment] 2021-06-27 00:45
Do you think you could make a reproduction using Glitch for this?

**Comment by boxxxie** [comment] 2021-06-27 01:32
this is literally triggering for me for every fragment swap

i wasn't successfully able to get `up-content/up-document` working with glitch, i'm not sure how i can get a fragment swap working on glitch right now.

**Comment by triskweline** [comment] 2021-06-28 08:21
Here is a Glitch project that swaps a fragment: https://glitch.com/edit/#!/thread-whimsical-budget

**Comment by triskweline** [comment] 2021-07-13 10:25
Closing this issue as it cannot be reproduced.

**Comment by adam12** [comment] 2021-07-29 19:58
I found this today, and it was a tricky one to track down. Responses that don't set a doctype of HTML (`<!DOCTYPE html>`) seem to trigger it. Some sort of browser compatibility mode perhaps?

Code: https://glitch.com/edit/#!/sunset-time-angolatitan
Demo: https://sunset-time-angolatitan.glitch.me

Chrome Version 91.0.4472.164 (Official Build) (arm64)

**Comment by adam12** [comment] 2021-07-29 20:15
I wonder if this is something we can guard on inside Unpoly to aide in debugging.

```js
if (document.compatMode === 'BackCompat') {
  up.fail('Page rendered in quirks mode. Is a DOCTYPE declaration missing from the markup?')
}
```

or something.

**Comment by triskweline** [comment] 2021-08-03 10:24
The next version will not boot in quirks mode. The reason will be printed to the log.

**Closed** 2021-08-03 10:23 UTC
Labels: bug, confirmed
