### ISSUE TITLE
unpoly migrate doesn't rewrite up-cache="false"

### ISSUE THREAD

**Issue by boxxxie** [unpoly/unpoly#199] opened 2021-06-26 19:01 UTC
### Bug description

`<a up-cache="false">` doesn't work anymore and needs to be `<a up-clear-cache>`

**Comment by adam12** [comment] 2021-06-26 21:22
Do you mean it doesn't make a network request as you expect? or that it doesn't clear the cache?

**Comment by boxxxie** [comment] 2021-06-26 21:45
i don't know how to observe the cache.

no network requests are made, i have to use `up-clear-cache`

migrate.js does not seem to make this change

**Comment by adam12** [comment] 2021-06-27 00:42
I can't reproduce. Can you look at my Glitch and see if you can reproduce it? https://glitch.com/edit/#!/dot-shell-balloon

**Comment by triskweline** [comment] 2021-07-13 10:25
Closing this issue as it cannot be reproduced.

**Closed by triskweline** 2021-07-13 10:25 UTC
Labels: reproduction needed
