### ISSUE TITLE
If up-target has multiple targets in different layers something weird happens 

### ISSUE THREAD

**Issue by okliv** [unpoly/unpoly#181] opened 2021-06-16 13:41 UTC
I have in `page` layer a table with `td>div.status` and a link with `up-modal=".modal"` to open a modal window for this table row and a modal itself with actually the same `.modal .status` div and link with `up-target="td>.status, .modal .status"`. If i click on it, it closes popup and replaces whole `body` with single `div.status` like when `up-target` is misconfigured.

But i expect that unpoly just will replace `div.status` in `page` layer (in a table at visible background) and in a modal (leaving modal opened)

If i leave only one of targets `td>.status` or `.modal .status` it works like expected: replaces status in a table's td or in a modal html respectively (leaving it opened).

Am i doing something wrong or this case is a subject for unpoly enhancement?

(unpoly 1.0.0)

Thanks

**Comment by adam12** [comment] 2021-06-16 14:36
Can you [enable logging](https://unpoly.com/up.log.enable) and share the relevant entries?

**Comment by okliv** [comment] 2021-06-16 23:09
`.status` here is `.issue_complex_issue_rec1zrJmJONCoyj6W`

![image](https://user-images.githubusercontent.com/884634/122306298-db439d80-cf10-11eb-893e-46b78824c642.png)

**Comment by okliv** [comment] 2021-06-16 23:15
i read it carefully and looks like it tries to extract `td>.status` and `.modal .status` from response but response has only `.modal 
 .status`... do i have to modify response and include in it unnecessary duplicate of same content wrapped into `td` tag?

**Comment by adam12** [comment] 2021-06-17 00:01
Are you trying to duplicate the same result into both `td` and `.modal`? If so, why?

By default, Unpoly will close the modal if you target an element below the modal. You could try applying [`up-sticky`](https://unpoly.com/a-up-modal#up-sticky) to the link that opens the modal and see if that helps.

But if you're trying to duplicate the content into both elements, you'll need to return the contents twice most likely. Unpoly just replaces DOM elements, so the ones you want to replace need to both be present.

**Comment by okliv** [comment] 2021-06-17 06:30
Let's say we have a table of tasks. And each task details in a modal/popup. The task state can be edited inline in a table and in a modal too. In my case i edit it's state by pushing a link with up-target=".status". State of task - is just a word: new/in progress/closed. And so, when i push the link, which changes the state of task, i want that unpoly would replace a word "New" by word "In progress" (after successful server side validation/save of new state), for example, in both places - in a table and in a popup without page reloading.

In both places (table and modal popup) container for the task state has the same html class='status' and so it is expected that unpoly would replace it in both places. But my guess is: just because a modal and a table are in a different layers, unpoly doesn't do it like it happens if i have two same containers in the same layer. But modal/popup/table cell whatever - it is just an element of loaded interface and so, my proposition is that unpoly has to ignore layer as a restriction for it's action and has apply it to the whole html currently loaded, no matter what layer it is (layer in terms of unpoly - is more a visual thing, not a logical one)

**Comment by adam12** [comment] 2021-06-17 15:14
Thank you for clarifying. I think I can understand the problem a bit better.

I don't have a great suggestion for v1, so maybe someone else can chime in, but in v2, I think I'd personally handle this in two steps.

The first step works similar to how you're doing it; update the modal contents with the result of the link, but forget about the table row.

The second step is reloading the table / table row when the modal is dismissed. Where you open the modal, use the [`up-on-dismissed`](https://unpoly.com/a-up-layer-new#up-on-dismissed) attribute to reload the table with something like [`up.reload`](https://unpoly.com/up.reload). I'm not sure you can reload just a table row due to browser limitations, so you might have to resort to reloading the entire table.

Of course, you could probably still render both elements, and target them. I'm not sure how Unpoly will handle updating targets in two layers, so either you'll have to report back or maybe Henning knows.

**Comment by okliv** [comment] 2021-06-17 22:49
Thanks for suggestion.

The UI problem is that modal appears over tasks table on a semi-transparent background and so state of the task in a table is visible to user even when modal is in front of it. And so, if we talk about modern reactive behaviour of the application, it has to act in a modern manner, replacing any instances of same data simultaneously.

I've read about 2.0 release today and all features it has - they are great. Mostly. But i still do not understand why layer is so important entity for unpoly :). And even more, it received so many enhancements (i would call it unnecessary complications) in 2.0. Any modal/popup - is a unique DOM element and so it is possible to address it without any layer philosophy at all. Will try to understand it better. Maybe.

**Comment by adam12** [comment] 2021-06-18 00:07
> The UI problem is that modal appears over tasks table on a semi-transparent background and so state of the task in a table is visible to user even when modal is in front of it. And so, if we talk about modern reactive behaviour of the application, it has to act in a modern manner, replacing any instances of same data simultaneously.

Makes sense, but as a user I personally wouldn't care, since that content is covered by a transparent overlay. As long as it was up to date when the data was in focus again.

But I think there may be a few other options:

1. With Unpoly 2, you could publish an event on the server and then listen for that event on the client. Then do the reload inside the listener. Like `issue:status_changed` as the event, then `up.on('issue:status_changed', (evt) => { up.reload('table#issues') })` or something.

2. Listen for `up:link:follow` on that specific link (maybe a certain selector, or an Unpoly compiler), then trigger an `up.reload` as above.

**Comment by okliv** [comment] 2021-06-21 14:12
i set up `up-on-dismissed="up.reload('.status_unique_address')"` for a modal and it works (unpoly somehow remembers what to do with that address). it fires one more unnecessary call to server, but it is an acceptable solution. thanks!

I still think that this case is common enough to foresee it in API for having more elegant solution but can't dive deeper to be more convincing

**Comment by okliv** [comment] 2021-06-21 15:32
looks like `up-source` is ignored for `up-on-dismissed`. above solution still works, but in most ugly way: it requests whole issues table 300kb to get only 0.3kb from it to refresh one word. how can i tell `up-on-dismissed` to use `up-source`?

**Comment by adam12** [comment] 2021-06-21 21:36
What element was `up-source` attached to that Unpoly didn't use?

`up.reload` accepts a URL if you wanted to be specific about the URL to use when fetching an element. You could perhaps have a separate route just for this, and then force the URL to be the route that renders the updated element on it's own.

**Comment by triskweline** [comment] 2021-06-22 06:09
If you want to reload a small fragment and have concerns about a lot of HTML being rendered unnecessarily, pass a `{ url }` option as @adam12. Alternatively your server can observe an `X-Up-Target: .status_unique_address` selector and only render the targeted fragment.

Closing this issue as this is working as intended on V2.

**Closed by triskweline** 2021-06-22 06:09 UTC
Labels: question

**Comment by okliv** [comment] 2021-06-22 06:24
i did
    up-layer="new" up-dismissable="true" up-on-dismissed="up.reload('.#{item.state}', {url: '/#{item.state_path}'})"

and it worked, thanks.

just for the record, there are two problems here:
- possibility to update same instance of data simultaneously is absent
- i have to use unnecessary extra request to the server

if it is intended, then it is not designed well (it is constructive criticism, i hope, just to help make unpoly better). if my case is out of scope - it is weird but understandable. closing? let is be.

thanks again.

**Comment by adam12** [comment] 2021-06-22 11:17
> [`up-source`](https://unpoly.com/up-source) not working with [reloading](https://unpoly.com/up.reload) on layer dismissed as it implicitly described in API

I think I see the issue here. The `up-source` attribute would have been on the class you were selecting, not the link triggering the reload. Maybe a tweak to the documentation would make this clearer.

> possibility to update multiple instances of the same data simultaneously (on different layers) is absent(?)

You could probably achieve this yourself using the Javascript API directly. Maybe listen for the `up:fragment:loaded` event, determine if it is from an element you were expecting, and if so, call `up.render` with arguments to duplicate the response text into another element.

> and it worked, thanks.

Great!
