### ISSUE TITLE
Custom scroll bars breaks <html> with overflow-y hidden when closing modal dialog 

### ISSUE THREAD

**Issue by bichonnages** [unpoly/unpoly#106] opened 2019-12-20 16:29 UTC
Clients want custom scrollbars for their website, using css such as : ::-webkit-scrollbar / ::-webkit-scrollbar-track / ::-webkit-scrollbar-thumb

After adding the code for custom scrollbars within my main css file, if I close the opened modal, unpoly seems to add "overflow-y: hidden" to the html tag on Chrome browser

might be related to this? https://makandracards.com/makandra/55801-does-html-or-body-scroll-the-page (from https://unpoly.com/changes/0.60.0)

**Comment by triskweline** [comment] 2019-12-23 11:29
These styles are added to the document's scrolling element when a modal is opened. Otherwise you would see two scrollbars with a modal open, since the modal overlay brings its own scrollbar. When the modal is closed, the styles should be removed again.

We're using this with custom scrollbar styles all the time.

Please post a minimal test case on CodePen (or similar) so I can see what about this behavior surprised you.

**Comment by triskweline** [comment] 2020-10-23 13:42
Closing this for now as we cannot reproduce this issue.

If you manage to reproduce this in a CodePen, feel free to re-open.

**Closed by triskweline** 2020-10-23 13:42 UTC
Labels: reproduction needed
