### ISSUE TITLE
Back button won't trigger destructors

### ISSUE THREAD

**Issue by foobear** [unpoly/unpoly#24] opened 2017-07-31 12:49 UTC
Using the back button does not trigger destructors.

Since compilers would need to clean up event listeners bound to other elements (like `document`), they can not do that. The compiler will be re-initialized and re-register its event listener a second time.

Example files can be found here: https://gist.github.com/foobear/a9b2b2a678cdd948e934c0e61138a5b6

The example above was tested in Chrome 60 and Firefox 54.
I'm currently binding events to `$('body')` to work around the issue; the body tag is replaced when going back.

**Comment by triskweline** [comment] 2017-08-01 18:47
This issue can be reproduced with jQuery 3, not 2.

**Comment by foobear** [comment] 2017-08-02 12:06
Thanks for looking into that. Using jQuery 2 for the time being is an acceptable workaround for me.

**Comment by kratob** [comment] 2017-10-11 11:23
I actually cannot confirm this bug. Back button definitely calls destructors on jQuery 3.

However, I've run into an issue where a destructor crashed, causing all later destructors not to be called. The destructor belonged to a compiler outside the content that was usually replaced, so the problem mostly triggered when using the back button, but is actually not caused by the back button in the first place.

**Comment by triskweline** [comment] 2017-12-06 07:42
The jQuery 3 part of this issue is fixed with the 0.50.0 release.
You still need to make your destructors not throw errors :)

**Closed by triskweline** 2017-12-06 07:42 UTC
