### ISSUE TITLE
up-modal up-nav applying up-current class to current and previous <a>/nav-items

### ISSUE THREAD

**Issue by boxxxie** [unpoly/unpoly#148] opened 2021-01-22 17:29 UTC
This behaviour is only happening in a modal, when i refresh and work without a modal up-nav works as expected.

**Comment by adam12** [comment] 2021-01-22 18:05
Since you mentioned trying out the v2 branch, can you advise which version you saw this on?

**Comment by boxxxie** [comment] 2021-01-23 17:17
@adam12 i haven't been successful at compiling v2 (hk/layers) code, so whatever dist/unpoly.js is in master is what i'm using.

I get compile errors for the hk/layers branch that i don't know how to solve. i get compile errors for master, but i have been able to solve those.

**Comment by adam12** [comment] 2021-01-24 18:29
> so whatever dist/unpoly.js is in master is what i'm using.

Should be the release from the website then.

Could you reproduce this with something like Glitch? Or show me some of the markup that is being annotated with `up-current`? I'm not able to reproduce.

**Comment by adam12** [comment] 2021-03-06 00:43
Should I close this? Were you able to debug this further?

**Comment by adam12** [comment] 2021-03-23 13:16
Closing for now. If you're able to create a reproducible example I'd love to see it.

**Closed by adam12** 2021-03-23 13:16 UTC
Labels: reproduction needed
