### ISSUE TITLE
Allow custom navigation feedback

### ISSUE THREAD

**Issue by boxxxie** [unpoly/unpoly#413] opened 2022-08-14 17:16 UTC
### Bug description

`.up-active` on the input/form isn't always good enough, some frameworks want these classes in wrappers around those elements.

also sometimes requests happen too fast (in development mostly) so it is desirable to have some minimum render time for active inputs.

so i propose a generic `up-active` attribute, and `up-active-duration` attribute that are more flexible.

```js

// used for cleaning up event listeners
function invoke(f){f()};

up.compiler("[up-active]", function(element, data){
  const active_class = element?.getAttribute("up-active");
  const input = up.element.get(element, "input");
  const form = input.form;
  const min_duration_str = element?.getAttribute("up-active-duration") ?? "1000";
  const min_duration = parseInt(min_duration_str)
  let start_timestamp;

  if (!form){
    console.error("coudn't find form for [up-active] compiler", element, data);
    return;
  }

  if(!active_class){
    console.error("coudn't find class name for [up-active] element", element, data);
    console.error("use up-active=\"<class_name>\"");
    return;
  }

  let cleanup = [
    up.on(form, "up:form:submit", function(event, form) {
      start_timestamp = event.timeStamp
      element.classList.add(active_class);
    }),

    up.on(form, "up:fragment:loaded:reply", function(event, form) {
      let end_timestamp = event.timeStamp
      let event_duration = end_timestamp - start_timestamp
      let makeup_duration = min_duration - event_duration;
      up.util.timer(makeup_duration, () => element.classList.remove(active_class))
    })
  ];

  return function(){
    cleanup.forEach(invoke)
  };
});

// -------------------- elements/forms that made requests get a callback when requests is done --------------------

up.on("up:fragment:loaded", function(event) {
  // fire event back to origin (sorta acts like a callback)
  up.emit(event.origin, "up:fragment:loaded:reply", event);
});

```

example HTML:
in the below, up-active adds `loading` class to the `div.ui` when it's child input triggers form submits. the active class `loading` stays on the div for at least 10 seconds (1 second default)

```html
<div class="ui left icon input fluid large"
     up-active-duration="10000"
     up-active="loading">
    <input
        autofocus
        up-autosubmit
        up-history="false"
        up-cache="false"
        up-delay="500"
        name="company-search"
        type="text"
        placeholder="Company Search..." >
    <i class="search icon"></i>
</div>
```

**Comment by triskweline** [comment] 2022-08-25 09:12
Note that Unpoly 3 will also add an [`.up-loading` class on the fragment that is being targeted](http://triskweline.de/unpoly3-slides/#56).

> also sometimes requests happen too fast (in development mostly) so it is desirable to have some minimum render time for active inputs.

The `.up-active` class was meant to give feedback to the user while the user is loading. What is the reason you want to give feedback for an instantaneous interaction?

> .up-active on the input/form isn't always good enough, some frameworks want these classes in wrappers around those elements.

I'm considering adding `up:feedback:start` and `up:feedback:stop` events so users can implement framework-specific integrations without Unpoly needing to support every case.

**Comment by boxxxie** [comment] 2022-08-25 21:44
sometimes an instantaneous action in a dev environment is not one in production, and sometimes it's undesirable to have the act of feedback be such a small amount of time that the user may not see it. i know there are other ways of dealing with that issue, but this is very convenient for a lot of use case i run into.

**Comment by triskweline** [comment] 2023-11-10 20:32
Closing as duplicate of #513.

**Closed by triskweline** 2023-11-10 20:32 UTC
