### ISSUE TITLE
Successfully submitting a form within a layer with the param up-layer='root' closes the layer with up:layer:dismiss and not up:layer:accept event

### ISSUE THREAD

**Issue by GiampaoloF95** [unpoly/unpoly#598] opened 2024-03-15 10:50 UTC
### Bug description

Not sure if this is an expected behavior or really a bug, but here is my issue:

After successfully submitting a form I want to render the response I get from the server in the root layer and i can achieve that by adding `up-layer='root'` as a parameter to the form html. 
The issue I'm facing is that after successfully submitting the form within the layer, it closes with the up:layer:dismiss and not up:layer:accept event.

### Reproduction project

[Test](https://form-root-bug-unpoly.glitch.me) I have enabled the logs to show the events triggered in the console

[Code](https://glitch.com/edit/#!/form-root-bug-unpoly)

### Steps to reproduce the behavior:

1. Create a form in an overlay with the `up-layer='root'` parameter in the form html
2. Open the form within the layer
3. Submit the form and observe the events that have been triggered

### Expected behavior

I expect that a successfully submitted form would always trigger the `up:layer:accept` and `up:layer:accepted` events as it has not been **dismissed** but it has been **accepted**

### Browser version

Tested on 
 - OS: Ubuntu 20.04.6
 - Browser: Chrome
 - Version: 122.0.6261.111

**Comment by triskweline** [comment] 2024-03-18 09:26
It's the intended behavior. Unpoly can't know if targeting another layer constitutes a positive or negative close intent, so it just defaults to dismiss.

[All other methods of closing overlays](https://unpoly.com/closing-overlays) allow you to be explicit about your close intent.

**Closed by triskweline** 2024-03-18 09:26 UTC
