### ISSUE TITLE
Content of Hidden Form Field is missing (sometimes)

### ISSUE THREAD

**Issue by MSchmidt** [unpoly/unpoly#134] opened 2020-08-28 10:14 UTC
I'm running into a weird issue I cannot reproduce myself. But since I don't get anywhere with this I'm posting it here for someone with a better understanding of the internals. Maybe you have a clue how this could be connected.

On a regular form I'm providing I have a hidden form field. For some reason the content of that field is not send via unpoly-based POST-Requests sometimes. So far it seems to affect only users on Firefox on Windows. The value is just missing. All other values are there.

I'm suspecting some kind of caching issue. Is there a certain situation that could ignore fields from being cached? Or from being submitted?

If you feel like this is not an unpoly issue, feel free to close this. However, the errors about this only started to show up once we moved that form to unpoly.

**Comment by adam12** [comment] 2020-08-28 14:14
The fact that it only happens sometimes does make this fairly strange. Are you manipulating the value at all (ie. setting it as the token from a Stripe response)? Any chance it could be a race condition?

What version of Unpoly?
Name of the hidden field?

I made a quick example and couldn't reproduce it here. Firefox 79.0 (64-bit) on Microsoft Windows [Version 10.0.19041.450]. https://repl.it/@adam121/HeftyLazyButtons

**Comment by triskweline** [comment] 2020-10-23 12:12
Closing this for now since we cannot reproduce the issue.

If you can reproduce this in a Codepen, feel free to re-open.

**Closed by triskweline** 2020-10-23 12:12 UTC
