### ISSUE TITLE
Why forms is submitted "weird" with unpoly, AKA: Is not compatible with rust serde.

### ISSUE THREAD

**Issue by mamcx** [unpoly/unpoly#121] opened 2020-05-21 17:23 UTC
I'm looking for a solution alike turbolinks to pair with rust [actix](https://actix.rs) server.

When submit a form with this, the request data look like:

```
multipart/form-data
-----------------------------60231461642893334112780192898
Content-Disposition: form-data; name="days"

76
-----------------------------60231461642893334112780192898
Content-Disposition: form-data; name="authorized"


-----------------------------60231461642893334112780192898
Content-Disposition: form-data; name="delivery_order"

0
-----------------------------60231461642893334112780192898
Content-Disposition: form-data; name="notes"

Content-Disposition: form-data; name="version"

31
-----------------------------60231461642893334112780192898
Content-Disposition: form-data; name="crud"

UPDATE
-----------------------------60231461642893334112780192898
Content-Disposition: form-data; name="geo_ip"


-----------------------------60231461642893334112780192898
Content-Disposition: form-data; name="action"

Confirm
-----------------------------60231461642893334112780192898--

```

This look very weird, is the first time I see something like this. Normally, the rust code expect:

```
application/x-www-form-urlencoded
action=Confirm&days=76&authorized=&delivery_order=0&notes=&version=31&crud=UPDATE&geo_ip=
```

**Comment by triskweline** [comment] 2020-05-23 16:19
We're using `multipart/form-data` since that allows us to transfer all kinds of form values, even binary blobs.

This is a duplicate of issue #107. Closing this in favor of #107.

**Closed by triskweline** 2020-05-23 16:19 UTC
Labels: duplicate

**Comment by naturallymitchell** [comment] 2020-05-23 20:29
@mamcx , It looks like Actix Web users need to use [actix-multipart](https://github.com/actix/actix-web/tree/master/actix-multipart) or another [Rust parser generator](https://github.com/kevinmehall/rust-peg#comparison-with-similar-parser-generators).  If you want a more robust development path for Actix Web, see also Torchbear and its related issue:
