### ISSUE TITLE
up-validate on input[type=date] with flatpicker not working since 3.x

### ISSUE THREAD

**Issue by marc-mabe** [unpoly/unpoly#488] opened 2023-05-12 08:53 UTC
### Bug description

I have a form with a date element and up-validate.
Additionally I'm using flatpicker to render a nice date picker.
Flatpicker itself changes the input type from date to text to disable the browsers native date picker.

Since 3.0 unpoly decided to listen on blur event instead of change event for date inputs in https://github.com/unpoly/unpoly/issues/336

Now if I change the date the following will happen:

**Case 1:** flatpicker is faster then unpoly
unpoly listens on change event because it's already a text input and everything works fine.

**Case 2:** unpoly is faster then flatpicker (usual case)
unpoly listens on blur event and flatpicker changes the input type to text afterwards.
As a result, if I select a date, the form gets submitted with the previous value and re-rendered with the previous value. So it's impossible to change the date.

### Reproduction project
https://awake-dear-taxicab.glitch.me/

### Steps to reproduce the behavior:

Please check what gets submitted on changing the first date (this should be the change event)
and what happens on changing the second date (this should be the blur event).
PS: Please reload the page after in between as the server does not respond correctly.

1. Go to reproduction project linked above
2. See event used on first date is `change`
3. Change first date
4. see it has submitted first date correctly
5. See event used on second date is `blur`
6. Change second date
7. see it has submitted initial value ignoring your selection

### Expected behavior

The selected date should be submitted.

### Browser version

 - OS: Linux
 - Browser FF 112.0.2 / Google Chrome 113.0.5672.63

### Additional context

I get the issue to be solved in #336 but as you see trying to be smart and changing behavior from one type to another most probably introduces new issues.
I'm not sure what a proper workaround for #336 would be but if the browser(s) decided that changing only parts of the date immediately fires a change event then this is what it is. An alternative could be to not submit the form on up-validate as long as the field changed is not valid according to browser field validation (this would include all fields like text inputs with pattern as well)

**Comment by triskweline** [comment] 2023-05-12 10:43
> Case 1: flatpicker is faster then unpoly
> Case 2: unpoly is faster then flatpicker (usual case)

What causes the initialization order to not be deterministic?

Consider using a compiler to initialize flatpicker instead of `MutationObserver`. This way `[up-validate]` should always run before your flat picker initialization. The order can be changed with a `{ priority }` option.

> Flatpicker itself changes the input type from date to text to disable the browsers native date picker.

It seems the issue is the input element changing its type after initialization, which Unpoly cannot support.

I'm closing this issue as there are numerous workarounds:

- Using text inputs instead of date inputs (if they're going through flatpicker anyway)
- Adding `[up-watch-event=change]` to date inputs, manually or with a macro
- Initializing flatpicker before `[up-validate]`
- Configuring [`up.form.config.watchChangeEvents`](https://unpoly.com/up.form.config#config.watchChangeEvents) to not watch `blur` events for date inputs.

**Comment by marc-mabe** [comment] 2023-05-12 11:31
Hi @triskweline,

> Consider using a compiler to initialize flatpicker instead of MutationObserver. This way [up-validate] should always run before your flat picker initialization. The order can be changed with a { priority } option.
This was only for the minimal example - In real the flatpicker is behind a stimulus controller.

> I'm closing this issue as there are numerous workarounds:
> 
>     Using text inputs instead of date inputs (if they're going through flatpicker anyway)
Trying to avoid this as the custom date picker needs javascript and the field should work fine without

>     Adding [up-watch-event=change] to date inputs, manually or with a macro
This seems to work 

>     Configuring [up.form.config.watchChangeEvents](https://unpoly.com/up.form.config#config.watchChangeEvents) to not watch blur events for date inputs.

OK this works - wasn't aware of such configuration yet.
Still wondering why there is a default "hack" in place making date input behave differently than all other inputs. If it's as simple to configure it to solve the issue in #336.
Especially as that's how all custom date pickers are working to disable browsers default behavior and as they are only needs sometimes they will be lazy loaded.

**Comment by triskweline** [comment] 2023-05-12 13:24
We can either provide a good default experience for people who use native date picker, or for people who use a custom date picker with the particular behavior of flatpickr.

I will think about changing the default to just `change`, but it looks like some group will always be surprised by the default.

**Comment by marc-mabe** [comment] 2023-05-12 13:59
I totally agree and it's not my decision.

I just would feel it consistent to say by default unpoly listens on the change event, which can be customized and probably with an example of date input instead of by default unpoly listens on change event except it's a date input which then defaults to blur.

**Closed** 2023-05-25 10:05 UTC
